version: "3.8"
services:
  freshrss:
    image: freshrss/freshrss:latest
    environment:
      TZ: Asia/Tokyo
      CRON_MIN: '*/60' # 60 分間隔で更新
    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/data/extensions:/var/www/FreshRSS/extensions
    ports: [ "8080:80" ]
    restart: unless-stopped

  rssbridge:
    image: rssbridge/rss-bridge:latest
    ports: [ "8081:80" ]
    restart: unless-stopped

