---
apiVersion: v1
kind: Namespace
metadata:
  name: freshrss
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data-pv
  namespace: freshrss
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/docker-services/fresh-rss/freshrss/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - name: freshrss
        image: freshrss/freshrss:latest
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: CRON_MIN
          value: '*/60'
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/www/FreshRSS/data
        - name: extensions
          mountPath: /var/www/FreshRSS/extensions
          subPath: extensions
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
      - name: extensions
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
spec:
  selector:
    app: freshrss
  ports:
  - port: 8080
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssbridge
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssbridge
  template:
    metadata:
      labels:
        app: rssbridge
    spec:
      containers:
      - name: rssbridge
        image: rssbridge/rss-bridge:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rssbridge
  namespace: freshrss
spec:
  selector:
    app: rssbridge
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30081
  type: NodePort